version: '3'

services:

        db:
                image: mysql:5.7
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: password
                        MYSQL_DATABASE: exampledb
                        MYSQL_USER: exampleuser
                        MYSQL_PASSWORD: examplepas
                volumes:
                        - db:/var/lib/mysql
        wordpress:
                image: wordpress:5.1.1-php7.3-apache
                restart: always
                ports:
                        - 8080:80
                depends_on:
                        - db
                volumes:
                        - wordpress:/var/www/html
                environment:
                        WORDPRESS_DB_HOST: db:3306
                        WORDPRESS_DB_USER: exampleuser
                        WORDPRESS_DB_PASSWORD: examplepass
                        WORDPRESS_DB_NAME: exampledb
volumes:
        db:
        wordpress:
